name: GitHub Actions Deploy
run-name: Building / deploying
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: install python deps
        run: pip install -r ./requirements.txt

      - name: Downloading new csv data
        run: bash ./scripts/get_exported.sh
        shell: bash
        env:
          TRAVIS: 1
          GOOGLE_DOC_ID: ${{ secrets.GOOGLE_DOC_ID }}

      - name: Building
        run: bash ./scripts/build.sh
        shell: bash
        env:
          TRAVIS: 1

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploying to www.randonneur.me
        run: bash ./scripts/ftp_deploy.sh
        shell: bash
        env:
          TRAVIS: 1
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
